# Generated by Django 5.2.8 on 2026-06-21 10:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('PRINT', 'Print/PDF'), ('BACKUP', 'Backup'), ('RESTORE', 'Restore'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('module', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_logs__action_235999_idx'), models.Index(fields=['module'], name='audit_logs__module_77713d_idx'), models.Index(fields=['created_at'], name='audit_logs__created_0fc90a_idx'), models.Index(fields=['user'], name='audit_logs__user_id_a5e0ec_idx')],
            },
        ),
    ]
