# Generated by Django 5.2.8 on 2026-06-19 21:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=100)),
                ('family_group_name', models.CharField(blank=True, max_length=150)),
                ('family_relationship', models.CharField(blank=True, max_length=100)),
                ('medical_history', models.TextField(blank=True)),
                ('allergy_history', models.TextField(blank=True)),
                ('eye_complaint', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('surgery_procedure_details', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('PART_PAYMENT', 'Part Payment'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['file_number'], name='patients_pa_file_nu_158006_idx'), models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx'), models.Index(fields=['phone_number'], name='patients_pa_phone_n_933975_idx'), models.Index(fields=['registration_date'], name='patients_pa_registr_b5cb97_idx')],
            },
        ),
    ]
