# Generated by Django 5.2.8 on 2026-06-19 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('family_name', models.CharField(max_length=150)),
                ('head_of_family', models.CharField(blank=True, max_length=150)),
                ('primary_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['family_name'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='patients.familygroup'),
        ),
        migrations.AddIndex(
            model_name='familygroup',
            index=models.Index(fields=['family_code'], name='patients_fa_family__156247_idx'),
        ),
        migrations.AddIndex(
            model_name='familygroup',
            index=models.Index(fields=['family_name'], name='patients_fa_family__c74088_idx'),
        ),
        migrations.AddIndex(
            model_name='familygroup',
            index=models.Index(fields=['primary_phone'], name='patients_fa_primary_7672c5_idx'),
        ),
    ]
