# Generated by Django 5.2.8 on 2026-06-19 23:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_familygroup_patient_family_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_type', models.CharField(choices=[('NEW_CONSULTATION', 'New Consultation'), ('FOLLOW_UP', 'Follow Up'), ('EMERGENCY', 'Emergency'), ('SURGERY_REVIEW', 'Surgery Review'), ('PROCEDURE', 'Procedure'), ('OTHER', 'Other')], default='NEW_CONSULTATION', max_length=30)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('WITH_NURSE', 'With Nurse'), ('WITH_DOCTOR', 'With Doctor'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=30)),
                ('chief_complaint', models.TextField(blank=True)),
                ('brief_history', models.TextField(blank=True)),
                ('temperature', models.CharField(blank=True, max_length=20)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('pulse', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
                'indexes': [models.Index(fields=['visit_number'], name='patients_pa_visit_n_834a32_idx'), models.Index(fields=['visit_date'], name='patients_pa_visit_d_6ebff6_idx'), models.Index(fields=['status'], name='patients_pa_status_4f8464_idx'), models.Index(fields=['visit_type'], name='patients_pa_visit_t_99b6d6_idx')],
            },
        ),
    ]
