# Generated by Django 5.2.8 on 2026-06-20 06:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenting_complaint', models.TextField(blank=True)),
                ('history_of_presenting_complaint', models.TextField(blank=True)),
                ('past_ocular_history', models.TextField(blank=True)),
                ('past_medical_history', models.TextField(blank=True)),
                ('drug_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('provisional_diagnosis', models.TextField(blank=True)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('consultation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_done', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='patients.patientvisit')),
            ],
            options={
                'ordering': ['-consultation_date'],
            },
        ),
        migrations.CreateModel(
            name='EyeExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_visual_acuity', models.CharField(blank=True, max_length=50)),
                ('left_visual_acuity', models.CharField(blank=True, max_length=50)),
                ('right_pinhole', models.CharField(blank=True, max_length=50)),
                ('left_pinhole', models.CharField(blank=True, max_length=50)),
                ('right_near_vision', models.CharField(blank=True, max_length=50)),
                ('left_near_vision', models.CharField(blank=True, max_length=50)),
                ('right_sphere', models.CharField(blank=True, max_length=30)),
                ('right_cylinder', models.CharField(blank=True, max_length=30)),
                ('right_axis', models.CharField(blank=True, max_length=30)),
                ('left_sphere', models.CharField(blank=True, max_length=30)),
                ('left_cylinder', models.CharField(blank=True, max_length=30)),
                ('left_axis', models.CharField(blank=True, max_length=30)),
                ('right_iop', models.CharField(blank=True, max_length=30)),
                ('left_iop', models.CharField(blank=True, max_length=30)),
                ('external_exam', models.TextField(blank=True)),
                ('anterior_segment', models.TextField(blank=True)),
                ('posterior_segment', models.TextField(blank=True)),
                ('fundus_exam', models.TextField(blank=True)),
                ('slit_lamp_exam', models.TextField(blank=True)),
                ('right_eye_findings', models.TextField(blank=True)),
                ('left_eye_findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('examination_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_examinations_done', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eye_examination', to='patients.patientvisit')),
            ],
            options={
                'ordering': ['-examination_date'],
            },
        ),
    ]
