# Generated by Django 5.2.8 on 2026-06-20 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_diagnosistreatment_prescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('procedure_name', models.CharField(max_length=200)),
                ('procedure_type', models.CharField(blank=True, max_length=150)),
                ('eye_side', models.CharField(choices=[('RIGHT', 'Right Eye'), ('LEFT', 'Left Eye'), ('BOTH', 'Both Eyes'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('procedure_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='PLANNED', max_length=30)),
                ('pre_op_diagnosis', models.TextField(blank=True)),
                ('post_op_diagnosis', models.TextField(blank=True)),
                ('procedure_notes', models.TextField(blank=True)),
                ('anesthesia_type', models.CharField(blank=True, max_length=100)),
                ('complications', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('post_op_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_as_assistant', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_records_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patients.patient')),
                ('surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_as_surgeon', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='patients.patientvisit')),
            ],
            options={
                'ordering': ['-scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['procedure_number'], name='patients_su_procedu_3de65d_idx'), models.Index(fields=['procedure_name'], name='patients_su_procedu_8ad776_idx'), models.Index(fields=['procedure_type'], name='patients_su_procedu_478029_idx'), models.Index(fields=['status'], name='patients_su_status_14a260_idx'), models.Index(fields=['scheduled_date'], name='patients_su_schedul_16764f_idx')],
            },
        ),
    ]
