# Generated by Django 5.2.8 on 2026-06-20 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_surgeryprocedure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('appointment_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow Up'), ('SURGERY', 'Surgery'), ('PROCEDURE', 'Procedure'), ('EYE_TEST', 'Eye Test'), ('OTHER', 'Other')], default='CONSULTATION', max_length=30)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=30)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'indexes': [models.Index(fields=['appointment_number'], name='patients_ap_appoint_617b82_idx'), models.Index(fields=['appointment_date'], name='patients_ap_appoint_c90b89_idx'), models.Index(fields=['status'], name='patients_ap_status_35223b_idx'), models.Index(fields=['appointment_type'], name='patients_ap_appoint_55e63e_idx')],
            },
        ),
    ]
