# Generated by Django 5.2.8 on 2026-08-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_bill_payment_bill_patients_bi_bill_nu_e43f74_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexamination',
            name='left_anterior_chamber',
            field=models.CharField(blank=True, choices=[('FORMED_CLEAR', 'Formed, Clear Media'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_anterior_chamber_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_conjunctiva',
            field=models.CharField(blank=True, choices=[('QUIET', 'Quiet'), ('INJECTION', 'Injection'), ('HYPERAEMIA', 'Hyperaemia'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_conjunctiva_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_cornea',
            field=models.CharField(blank=True, choices=[('CLEAR', 'Clear'), ('HAZY', 'Hazy'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_cornea_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_corrected_iop',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_disc_colour',
            field=models.CharField(blank=True, choices=[('PINK_NRR', 'Pink NRR'), ('PALE_NRR', 'Pale NRR'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_disc_colour_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_disc_margin',
            field=models.CharField(blank=True, choices=[('DISTINCT', 'Distinct'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_disc_margin_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_estimated_vcdr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_gonioscopy_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_iris',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_iris_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_lens',
            field=models.CharField(blank=True, choices=[('TRANSPARENT', 'Transparent'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_lens_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_lids_adnexa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_macula',
            field=models.CharField(blank=True, choices=[('BRIGHT_REFLEX', 'Bright reflex'), ('DULL_REFLEX', 'Dull reflex'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_macula_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_other_fundus_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_pupil',
            field=models.CharField(blank=True, choices=[('ROUND_REGULAR_REACTIVE', 'Round, Regular, Reactive'), ('RAPD', 'RAPD'), ('OTHER', 'Others (Specify)')], max_length=40),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_pupil_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_retina',
            field=models.CharField(blank=True, choices=[('PINK_FLAT', 'Pink, Flat'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_retina_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_vessels',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_vessels_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_vitreous',
            field=models.CharField(blank=True, choices=[('CLEAR_MEDIA', 'Clear media'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_vitreous_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_anterior_chamber',
            field=models.CharField(blank=True, choices=[('FORMED_CLEAR', 'Formed, Clear Media'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_anterior_chamber_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_conjunctiva',
            field=models.CharField(blank=True, choices=[('QUIET', 'Quiet'), ('INJECTION', 'Injection'), ('HYPERAEMIA', 'Hyperaemia'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_conjunctiva_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_cornea',
            field=models.CharField(blank=True, choices=[('CLEAR', 'Clear'), ('HAZY', 'Hazy'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_cornea_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_corrected_iop',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_disc_colour',
            field=models.CharField(blank=True, choices=[('PINK_NRR', 'Pink NRR'), ('PALE_NRR', 'Pale NRR'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_disc_colour_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_disc_margin',
            field=models.CharField(blank=True, choices=[('DISTINCT', 'Distinct'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_disc_margin_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_estimated_vcdr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_gonioscopy_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_iris',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_iris_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_lens',
            field=models.CharField(blank=True, choices=[('TRANSPARENT', 'Transparent'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_lens_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_lids_adnexa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_macula',
            field=models.CharField(blank=True, choices=[('BRIGHT_REFLEX', 'Bright reflex'), ('DULL_REFLEX', 'Dull reflex'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_macula_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_other_fundus_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_pupil',
            field=models.CharField(blank=True, choices=[('ROUND_REGULAR_REACTIVE', 'Round, Regular, Reactive'), ('RAPD', 'RAPD'), ('OTHER', 'Others (Specify)')], max_length=40),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_pupil_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_retina',
            field=models.CharField(blank=True, choices=[('PINK_FLAT', 'Pink, Flat'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_retina_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_vessels',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_vessels_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_vitreous',
            field=models.CharField(blank=True, choices=[('CLEAR_MEDIA', 'Clear media'), ('OTHER', 'Others (Specify)')], max_length=30),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_vitreous_other',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
