# Generated by Django 5.2.8 on 2026-08-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_eyeexamination_left_anterior_chamber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexamination',
            name='auto_refraction_remarks',
            field=models.TextField(blank=True, verbose_name='Auto Refraction Remarks'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='cycloplegic_agent',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('CYCLOPENTOLATE', 'Cyclopentolate'), ('TROPICAMIDE', 'Tropicamide'), ('ATROPINE', 'Atropine'), ('PHENYLEPHRINE', 'Phenylephrine'), ('OTHER', 'Others (Specify)')], max_length=30, verbose_name='Cycloplegic Agent'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='cycloplegic_agent_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='Other Cycloplegic Agent'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_dry_axis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Left Dry Axis'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_dry_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Left Dry Cylinder'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_dry_sphere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Left Dry Sphere'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_dry_spherical_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Left Dry Spherical Equivalent'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_lensometry',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lensometry — Left Eye'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_wet_axis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Left Wet Axis'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_wet_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Left Wet Cylinder'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_wet_sphere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Left Wet Sphere'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_wet_spherical_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Left Wet Spherical Equivalent'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_with_glasses',
            field=models.CharField(blank=True, max_length=50, verbose_name='Left Eye With Glasses'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_dry_axis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Right Dry Axis'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_dry_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Right Dry Cylinder'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_dry_sphere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Right Dry Sphere'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_dry_spherical_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Right Dry Spherical Equivalent'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_lensometry',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lensometry — Right Eye'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_wet_axis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Right Wet Axis'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_wet_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Right Wet Cylinder'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_wet_sphere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Right Wet Sphere'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_wet_spherical_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Right Wet Spherical Equivalent'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_with_glasses',
            field=models.CharField(blank=True, max_length=50, verbose_name='Right Eye With Glasses'),
        ),
    ]
