# Generated by Django 5.2.8 on 2026-08-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_eyeexamination_auto_refraction_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexamination',
            name='left_near_vision_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_pinhole_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_visual_acuity_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_with_glasses_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_near_vision_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_pinhole_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_visual_acuity_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_with_glasses_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
