# Generated by Django 5.2.8 on 2026-08-02 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_eyeexamination_left_near_vision_other_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexamination',
            name='left_subjective_add_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Left Add Power'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_subjective_aided_va',
            field=models.CharField(blank=True, max_length=50, verbose_name='Left Aided Visual Acuity'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_subjective_aided_va_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Left Aided Visual Acuity'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_subjective_axis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Left Subjective Axis'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_subjective_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Left Subjective Cylinder'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_subjective_near_vision',
            field=models.CharField(blank=True, max_length=50, verbose_name='Left Subjective Near Vision'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_subjective_near_vision_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Left Subjective Near Vision'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='left_subjective_sphere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Left Subjective Sphere'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_subjective_add_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Right Add Power'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_subjective_aided_va',
            field=models.CharField(blank=True, max_length=50, verbose_name='Right Aided Visual Acuity'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_subjective_aided_va_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Right Aided Visual Acuity'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_subjective_axis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Right Subjective Axis'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_subjective_cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Right Subjective Cylinder'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_subjective_near_vision',
            field=models.CharField(blank=True, max_length=50, verbose_name='Right Subjective Near Vision'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_subjective_near_vision_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Right Subjective Near Vision'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='right_subjective_sphere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Right Subjective Sphere'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_bifocal_type',
            field=models.CharField(blank=True, choices=[('D_TOP', 'D-Top'), ('EXECUTIVE', 'Executive'), ('FUSED', 'Fused'), ('VARILUX', 'Varilux'), ('OTHER', 'Others (Specify)')], max_length=30, verbose_name='Bifocal Type'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_bifocal_type_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='Other Bifocal Type'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_dispensary_instruction',
            field=models.CharField(blank=True, choices=[('BIFOCAL', 'Bifocal'), ('SEPARATE', 'Separate'), ('DISTANCE_ONLY', 'Distance Only'), ('NEAR_ONLY', 'Near Only'), ('OTHER', 'Others (Specify)')], max_length=30, verbose_name='Dispensary Instruction'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_dispensary_instruction_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='Other Dispensary Instruction'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_distance_pd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance pupillary distance in millimetres.', max_digits=5, null=True, verbose_name='Distance PD'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_lens_type',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('WHITE_AR', 'White A/R'), ('PHOTO_AR', 'Photo A/R'), ('VARILUX', 'Varilux'), ('REGULAR_BLUE_COAT', 'Regular Blue Coat'), ('ORIGINAL_BLUE_COAT', 'Original Blue Coat'), ('OTHER', 'Others (Specify)')], max_length=40, verbose_name='Lens Type'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_lens_type_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='Other Lens Type'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_near_pd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Near pupillary distance in millimetres.', max_digits=5, null=True, verbose_name='Near PD'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_refraction_approved',
            field=models.BooleanField(default=False, verbose_name='Subjective Refraction Approved'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_refraction_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_refraction_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_subjective_refractions', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_refraction_diagnosis',
            field=models.TextField(blank=True, verbose_name='Subjective Refraction Diagnosis'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_refraction_history',
            field=models.TextField(blank=True, verbose_name='Subjective Refraction History'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_refraction_remarks',
            field=models.TextField(blank=True, verbose_name='Subjective Refraction Remarks'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_wearing_instruction',
            field=models.CharField(blank=True, choices=[('DISTANCE_ONLY', 'Distance Only'), ('NEAR_ONLY', 'Near Only'), ('REGULAR_WEAR', 'Regular Wear'), ('OTHER', 'Others (Specify)')], max_length=30, verbose_name='Wearing Instruction'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='subjective_wearing_instruction_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='Other Wearing Instruction'),
        ),
    ]
