# Generated by Django 5.2.8 on 2026-08-02 21:23

import django.core.validators
import django.db.models.deletion
import patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_eyeexamination_left_subjective_add_power_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OCT', 'OCT Scan'), ('FUNDUS_PHOTO', 'Fundus Photograph'), ('VISUAL_FIELD', 'Visual Field Test'), ('B_SCAN', 'B-Scan Ultrasound'), ('CORNEAL_TOPOGRAPHY', 'Corneal Topography'), ('OPTICAL_BIOMETRY', 'Optical Biometry'), ('FLUORESCEIN_ANGIOGRAPHY', 'Fluorescein Angiography'), ('LENSOMETRY', 'Lensometry Report'), ('LAB_RESULT', 'Laboratory Result'), ('RADIOLOGY', 'Radiology Report'), ('REFERRAL_LETTER', 'Referral Letter'), ('OPERATION_NOTE', 'Operation Note'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('INSURANCE_DOCUMENT', 'Insurance Document'), ('CONSENT_FORM', 'Consent Form'), ('EXTERNAL_REPORT', 'External Medical Report'), ('OTHER', 'Others (Specify)')], max_length=40)),
                ('category_other', models.CharField(blank=True, max_length=150, verbose_name='Other Category')),
                ('eye_side', models.CharField(choices=[('RIGHT', 'Right Eye'), ('LEFT', 'Left Eye'), ('BOTH', 'Both Eyes'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='File Title')),
                ('description', models.TextField(blank=True, verbose_name='Comment / Description')),
                ('investigation_date', models.DateField(blank=True, null=True, verbose_name='Investigation Date')),
                ('attachment_file', models.FileField(upload_to=patients.models.clinical_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Clinical File')),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('file_extension', models.CharField(blank=True, editable=False, max_length=20)),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False, help_text='File size in bytes.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('NEEDS_ATTENTION', 'Needs Attention')], default='PENDING', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive attachments remain recorded for audit purposes but are hidden from normal clinical lists.')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_attachments', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_clinical_attachments', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_clinical_attachments', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_attachments', to='patients.patientvisit')),
            ],
            options={
                'verbose_name': 'Clinical Attachment',
                'verbose_name_plural': 'Clinical Attachments',
                'ordering': ['-investigation_date', '-uploaded_at'],
                'indexes': [models.Index(fields=['patient', 'uploaded_at'], name='clinical_att_patient_date_idx'), models.Index(fields=['visit', 'category'], name='clinical_att_visit_cat_idx'), models.Index(fields=['review_status'], name='clinical_att_review_idx'), models.Index(fields=['is_active'], name='clinical_att_active_idx')],
            },
        ),
    ]
