# Generated by Django 5.2.8 on 2026-08-03 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_clinicalattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalImageAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Clinical Annotation', max_length=200)),
                ('clinical_note', models.TextField(blank=True, verbose_name='Clinical Annotation Note')),
                ('annotation_data', models.JSONField(blank=True, default=dict, help_text='Normalized vector drawing instructions. The original clinical image remains unchanged.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_annotations', to='patients.clinicalattachment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_annotations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clinical_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinical Image Annotation',
                'verbose_name_plural': 'Clinical Image Annotations',
                'ordering': ['-updated_at', '-pk'],
                'indexes': [models.Index(fields=['attachment', 'is_active'], name='img_ann_attach_active_idx'), models.Index(fields=['status', 'updated_at'], name='img_ann_status_date_idx')],
            },
        ),
    ]
