# Generated by Django 5.2.8 on 2026-06-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='CAPITAL EYE HOSPITAL', max_length=200)),
                ('system_name', models.CharField(default='CAPITAL EYE HOSPITAL RECORDS SYSTEM', max_length=200)),
                ('hospital_address', models.TextField(blank=True)),
                ('hospital_phone', models.CharField(blank=True, max_length=50)),
                ('hospital_email', models.EmailField(blank=True, max_length=254)),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for choosing Capital Eye Hospital.')),
                ('report_footer', models.TextField(blank=True, default='Generated from CAPITAL EYE HOSPITAL RECORDS SYSTEM.')),
                ('backup_reminder_text', models.CharField(default='Remember to backup clinic records regularly.', max_length=255)),
                ('default_currency', models.CharField(default='₦', max_length=10)),
                ('allow_duplicate_warning', models.BooleanField(default=True)),
                ('enable_audit_logs', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
